### ISSUE TITLE
Scrapping de mails

### ISSUE THREAD

**Issue by etienne-lelouet** [slipsoft/slipspam#2]
Rendre des mails cohérents avec nos jeux de données (mail anglais spam / non spam, BDD en lignes existantes)

**Comment by n-peugnet** [comment]
Un jeu de données possible, enfin à voir:
https://www.kaggle.com/abhiroyq1/spam-mail-dataset

Edit:
celui-ci a l'air mieux:
https://www.kaggle.com/karthickveerakumar/spam-filter

Edit2:
bon voilà la source en fait:
https://www.kaggle.com/datasets?sortBy=relevance&group=public&search=spam&page=1&pageSize=20&size=all&filetype=all&license=all

**Comment by n-peugnet** [comment]
Le data mining de mails est fini avec la commande parse.
Je ferme
