### ISSUE TITLE
combine all confusion matrices into one

### ISSUE THREAD

**Issue by n-peugnet** [slipsoft/slipspam#4]
like this:

| algo | true | false|
|------|-------|------|
| knn true | 98 | 2 |
| mlp true | 99 | 1 |
| knn false | 7 | 93 |
| mlp false | 2 | 98 |

_avec un peu de chance il y a une fonction numpy qui fait exactement ça..._

**Comment by SylvainJoube** [comment]
Alors comme ça on fait des commits alors qu'on est au travail, Monsieur Peugnet ? :o

**Comment by n-peugnet** [comment]
bah c pas un commit, c'est une issue pour noter les trucs que j'ai à faire pour pas oublier

**Comment by SylvainJoube** [comment]
Bon, j'avoue, j'avoue, t'as raison ;)
Tu peux aussi me retourner ma phrase, je suis au taf là, et pas en congés ! ;)
Ça a l'air grave cool ce que vous faites, en tout cas !

**Comment by n-peugnet** [comment]
> Ça a l'air grave cool ce que vous faites, en tout cas !

mais tu sais ce que c'est en plus, c'est le truc que j'ai galéré à rendre cohérent samedi _matin_ chez toi !
(cf le dernier commit : e685ec71)

**Comment by SylvainJoube** [comment]
> 
> 
> > Ça a l'air grave cool ce que vous faites, en tout cas !
> 
> mais tu sais ce que c'est en plus, c'est le truc que j'ai galéré à rendre cohérent samedi _matin_ chez toi !
> (cf le dernier commit : [e685ec7](https://github.com/slipsoft/slipspam/commit/e685ec7134e0a8025cdb60fc06f65d4cb40ac425))

Yap ! Je m'en souviens très bien ^-^ C'est zouliiiiiiiii :)
